# Generated by Django 4.1.3 on 2022-11-20 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0003_program_complementary_courses'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courses',
            name='pre_reqs',
        ),
    ]
