# Generated by Django 4.1.3 on 2022-11-20 09:21

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0004_remove_courses_pre_reqs'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='pre_reqs',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=10), default=list, size=8), default=list, size=8),
        ),
    ]
