# Generated by Django 4.1.3 on 2022-11-20 10:20

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0006_alter_courses_pre_reqs_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='pre_reqs',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=200), default=list, size=None),
        ),
        migrations.AlterField(
            model_name='program',
            name='complementary_courses',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=200), default=list, size=None),
        ),
    ]
